#!/bin/bash
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
#echo 552523 |sudo find / -name guacamole
export PATH=$PATH:/usr/local/go/bin
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
screen_name=`python ~/bash_sample/fuck.py`
myFlag=`expr substr "$screen_name" 1 3`
myName=`echo ${screen_name:4}`
echo $screen_name
echo $myFlag
yes="yes"
nop="nop"

if [ "$myFlag" = "$nop" ];then
	echo $myName
	#echo "nimabi"
	screen -dmS $myName
	screen -r $myName <<eof
	552523
eof
fi
if [ "$myFlag" = "$yes" ];then
	echo $myName
	echo "caonima"
	screen -r $myNamea <<eof
	552523
eof
fi
#clear
